tasks:
  - name: htmlbeautifier
    init: gem install htmlbeautifier
  - name: rufo
    init: gem install rufo
  - name: heroku
    init: curl https://cli-assets.heroku.com/install.sh | sh
  - name: postgres
    init: sudo apt-get update && sudo apt-get install -y nodejs yarn postgresql-client
  - name: postgres2
    init: sudo apt install -y postgresql postgresql-contrib libpq-dev psmisc lsof
  - name: setup
    init: bin/setup
github:
  prebuilds:
    branches: true
    addBadge: true
    pullRequestsFromForks: true
    addLabel: true
ports:
  - port: 3000
    onOpen: open-preview
    
vscode:
  extensions:
    - shd101wyy.markdown-preview-enhanced@0.5.1:s3vD5qiY6/HbtRrgDlbMiQ==
    - vortizhe.simple-ruby-erb@0.2.1:BzpDuNAqJwUkxqT2t1YIuQ==
    - CraigMaslowski.erb@0.0.1:5znDha/nn0PphUrpB9a5Nw==
    - Vense.rails-snippets@0.5.0:w1Rd4bmOp7tM7xc3UJruRQ==
    - wingrunr21.vscode-ruby@0.26.0:VakXVw0C77hAQ3U3AZTn1Q==
    - aliariff.vscode-erb-beautify@0.2.0:JPBIiJcuf3dj5jx4nE7u8Q==
